os:
    - linux

language: python

python:
    - pypy
    - 3.5
    - 3.6

before_script:
    - pip install -r requirements-dev.txt

script:
    - python sh.py travis
    - if python -c 'import sys; sys.exit(int(not sys.version_info >= (3, 5)))' ; then python setup.py check --restructuredtext --metadata --strict ; fi

after_success:
    - coveralls
