os:
    - linux

language: python

python:
    - 3.6
    - 3.7
    - 3.8
    - 3.9
    - pypy

before_script:
    - poetry install -D

script:
    - python sh.py travis
    - python -m flake8 sh.py test.py
    - if python -c 'import sys; sys.exit(int(not sys.version_info >= (3, 8)))' ; then python setup.py check --restructuredtext --metadata --strict ; fi

after_success:
    - coveralls
